package com.busanit501.androidlabtest501.miniProject.test0709.ngy0428_mini

import androidx.recyclerview.widget.RecyclerView
import com.busanit501.androidlabtest501.databinding.Ch11ItemSimpleRecycler2Binding
import com.busanit501.androidlabtest501.databinding.Ch11ItemSimpleRecyclerBinding
import com.busanit501.androidlabtest501.databinding.NgyCh11ItemSimpleRecycler3Binding

class Ch11MyViewHolder3(val binding: NgyCh11ItemSimpleRecycler3Binding): RecyclerView.ViewHolder(binding.root) {
}